export const useColorsVariants = () => {
    const colorVariants = {
        blue: 'bg-blue-400',
        red: 'bg-red-400',
        yellow: 'bg-yellow-400',
        green: 'bg-green-400',
        slate: 'bg-slate-400',
        orange: 'bg-orange-400',
        pink: 'bg-pink-400',
        purple: 'bg-purple-400',
        cyan: 'bg-cyan-400',
        gray: 'bg-gray-400',
        zinc: 'bg-zinc-400',
        neutral: 'bg-neutral-400',
        amber: 'bg-amber-400',
        lime: 'bg-lime-400',
        emerald: 'bg-emerald-400',
        teal: 'bg-teal-400',
        sky: 'bg-sky-400',
        indigo: 'bg-indigo-400',
        violet: 'bg-violet-400',
        fuchsia: 'bg-fuchsia-400',
        rose: 'bg-rose-400',
        stone: 'bg-stone-400',
    }

    const colorVariantsTextHover = {
        blue: 'hover:text-blue-400',
        red: 'hover:text-red-400',
        yellow: 'hover:text-yellow-400',
        green: 'hover:text-green-400',
        slate: 'hover:text-slate-400',
        orange: 'hover:text-orange-400',
        pink: 'hover:text-pink-400',
        purple: 'hover:text-purple-400',
        cyan: 'hover:text-cyan-400',
        gray: 'hover:text-gray-400',
        zinc: 'hover:text-zinc-400',
        neutral: 'hover:text-neutral-400',
        amber: 'hover:text-amber-400',
        lime: 'hover:text-lime-400',
        emerald: 'hover:text-emerald-400',
        teal: 'hover:text-teal-400',
        sky: 'hover:text-sky-400',
        indigo: 'hover:text-indigo-400',
        violet: 'hover:text-violet-400',
        fuchsia: 'hover:text-fuchsia-400',
        rose: 'hover:text-rose-400',
        stone: 'hover:text-stone-400',
    }

    const colorVariantsLabel = {
        blue: 'text-blue-500 bg-blue-100',
        red: 'text-red-500 bg-red-100',
        yellow: 'text-yellow-500 bg-yellow-100',
        green: 'text-green-500 bg-green-100',
        slate: 'text-slate-500 bg-slate-100',
        orange: 'text-orange-500 bg-orange-100',
        pink: 'text-pink-500 bg-pink-100',
        purple: 'text-purple-500 bg-purple-100',
        cyan: 'text-cyan-500 bg-cyan-100',
        gray: 'text-gray-500 bg-gray-100',
        zinc: 'text-zinc-500 bg-zinc-100',
        neutral: 'text-neutral-500 bg-neutral-100',
        amber: 'text-amber-500 bg-amber-100',
        lime: 'text-lime-500 bg-lime-100',
        emerald: 'text-emerald-500 bg-emerald-100',
        teal: 'text-teal-500 bg-teal-100',
        sky: 'text-sky-500 bg-sky-100',
        indigo: 'text-indigo-500 bg-indigo-100',
        violet: 'text-violet-500 bg-violet-100',
        fuchsia: 'text-fuchsia-500 bg-fuchsia-100',
        rose: 'text-rose-500 bg-rose-100',
        stone: 'text-stone-500 bg-stone-100',
    }

    return { colorVariants,colorVariantsTextHover,colorVariantsLabel }
}