export const useColorsVariants = () => {
    const colorVariants = {
        blue: 'bg-blue-400',
        red: 'bg-red-400',
        yellow: 'bg-yellow-400',
        green: 'bg-green-400',
        slate: 'bg-slate-400',
        orange: 'bg-orange-400',
        pink: 'bg-pink-400',
        purple: 'bg-purple-400',
        cyan: 'bg-cyan-400',
        gray: 'bg-gray-400',
        zinc: 'bg-zinc-400',
        neutral: 'bg-neutral-400',
        amber: 'bg-amber-400',
        lime: 'bg-lime-400',
        emerald: 'bg-emerald-400',
        teal: 'bg-teal-400',
        sky: 'bg-sky-400',
        indigo: 'bg-indigo-400',
        violet: 'bg-violet-400',
        fuchsia: 'bg-fuchsia-400',
        rose: 'bg-rose-400',
        stone: 'bg-stone-400',
    }

    const colorVariantsTextHover = {
        blue: 'hover:text-blue-400',
        red: 'hover:text-red-400',
        yellow: 'hover:text-yellow-400',
        green: 'hover:text-green-400',
        slate: 'hover:text-slate-400',
        orange: 'hover:text-orange-400',
        pink: 'hover:text-pink-400',
        purple: 'hover:text-purple-400',
        cyan: 'hover:text-cyan-400',
        gray: 'hover:text-gray-400',
        zinc: 'hover:text-zinc-400',
        neutral: 'hover:text-neutral-400',
        amber: 'hover:text-amber-400',
        lime: 'hover:text-lime-400',
        emerald: 'hover:text-emerald-400',
        teal: 'hover:text-teal-400',
        sky: 'hover:text-sky-400',
        indigo: 'hover:text-indigo-400',
        violet: 'hover:text-violet-400',
        fuchsia: 'hover:text-fuchsia-400',
        rose: 'hover:text-rose-400',
        stone: 'hover:text-stone-400',
    }

    return { colorVariants,colorVariantsTextHover }
}